### ISSUE TITLE
core library roadmap

### ISSUE THREAD

**Issue by umegaya** [suntomi/qrpc#8]
### before 0.1.0
- [ ] client.js: migrate to typescript
- [ ] client.js: support multi host
- [ ] native client library
- [ ] server multi-client e2e
